cbeventforwarder/lib/event_processor.py
root/etc/cb/integrations/event-forwarder/cb-event-forwarder.conf.example

If AWS credentials are not found in the event-forwarder
configuration file, then use the boto library standard
search path to find them.

Make AWS credentials optional in the configuration file.

---

config.go
json_message_processor.go
leef/leef_encoder.go

`src` and `dst` IP addresses and ports were reversed in the LEEF output when processing netconn data from inbound connections

Fix directionality in LEEF output

---

README.md

Usage: cbcluster COMMAND [CMD OPTIONS]
Carbon Black Enterprise Response Server cluster management command line tool
Available commands are:
help        Display this help screen
start       Start the cluster
stop        Stop the cluster
status      Get the running status of the cluster
add-node    Add a slave node to the cluster
reshard     Split single process event store shard into N shards

update README.md there is no "cbcluster restart" command

---

conf/cb-event-forwarder.example.ini

Clarifying behavior in 5.2. I have verified `feeds.*.*.*` behavior, could not verify `watchlist.*.*.*` behaves the same way.

Comments to clarify 5.2 behavior in the example configuration

---

bundled_output.go

Output files can get created with the same filename and when uploaded to S3, they overwrite each other. This results in a loss of data for consumers.

Add milliseconds to filenames so they are less likely to collide

---

cb_api.go
conf/cb-event-forwarder.example.ini
config.go
main.go
pb_message_processor.go

TLS changes to provide a way to override the CN when validating certificates as well as force TLSv1.2 when connecting to the target syslog/http and Cb Response servers

TLS CN override

---

amqp.go
conf/cb-event-forwarder.example.ini
config.go

This adds a config option for manual acking, which might be desired in an environment to guarantee delivery.
This also exposes the `rabbit_mq_queue_name` config option in the config example which would be desired in a high throughput environment.

Create a config option for automatic vs manual acking

---

pb_message_processor.go

This PR adds the following fields that are present in the protobuf def but the the event forwarder 
CbProcessMsg - parent_pid
CbProcessMsg - parent_guid
CbProcessMsg - filtering_known_dlls
CbProcessMsg - tamper
CbProcessMsg - tamper_sent
CbChildProcessMsg - tamper
CbChildProcessMsg - tamper_sent
CbChildProcessMsg - parent_guid
CbRegModMsg - tamper
CbRegModMsg - tamper_sent

add missing fields for childprocs and a few other event types

---

config.go

This change was committed by me but broke things. I misunderstood the logic and it produces undesired outcomes. 
We want the `if` statements to only fall through to the else only if the `err == nil` does not pass.

Fix config logic parsing

---

cmd/cb-event-forwarder/config.go
cmd/cb-event-forwarder/main.go
conf/cb-event-forwarder.example.ini

This commit adds a setting `add_to_output` in the config, which allows one to add additional (static) metadata to events forwarded by the cb-event-forwarder.
The setting can be set to a sequence of key=value pairs, separated by commas. An example could be:
[bridge]
add_to_output=meta_location=some_city,meta_department=some_dept

Add config option to add additional key/value pairs

---

cmd/cb-event-forwarder/config.go
cmd/cb-event-forwarder/s3_behavior.go
conf/cb-event-forwarder.example.ini

Writing to s3 from an ipv6-only network requires the use of "dual stack" endpoints (see more [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/dual-stack-endpoints.html)). This PR adds an option in the config to use dual stack endpoints and then passes that option to the S3 client when it is created.

Add support for s3 from ipv6 networks

---

Gopkg.toml
Makefile
cmd/cb-event-forwarder/config.go
cmd/cb-event-forwarder/config_test.go
cmd/cb-event-forwarder/http_behavior.go
cmd/cb-event-forwarder/http_behavior_test.go
cmd/cb-event-forwarder/main.go
conf/cb-event-forwarder.example.ini

To learn more about OAuth 2.0 JSON Web Token flow, please refer to
https://tools.ietf.org/html/draft-ietf-oauth-jwt-bearer-12.

Add OAuth 2.0 JSON Web Token flow support to http output

---

Gopkg.toml
Makefile
cmd/cb-event-forwarder/config.go
cmd/cb-event-forwarder/http_util.go
cmd/cb-event-forwarder/http_util_test.go
cmd/cb-event-forwarder/main.go
conf/cb-event-forwarder.example.ini

Support outputing EventText as byte array field (i.e. binary field) when posting JSON to the remote service.
By default, EventText is output as JSON string field and the value of
EventText will be in UTF-8 encoded string. If EventText is output as
JSON byte array field, the value of EventText will be in base64-encoded string.

Support outputing EventText as byte array field

---

cmd/cb-event-forwarder/amqp.go
cmd/cb-event-forwarder/amqp_test.go
cmd/cb-event-forwarder/main.go

Fix a bug in the amqp consumer where NotifyClose wasn't working. Should address CB-30713 and the related escalation, based on my testing.
You can test this by running the rabbitmq management interface, and force-closing the aqmp connection from the event-forwarder.

CB-30713: Fixing NotifClose support in amqp consumer

---

Makefile
cb-event-forwarder.rpm.spec

RPMs now include a timestamp, e.g. `cb-event-forwarder-3.6.2.200319.1303-0.el6.x86_64.rpm`. I also bumped the version to 3.6.2

CB-30580: add timestamps

---

go.mod
scripts/deploy

The script is intended to be sourced into the Build section of a Jenkins job within an "Execute shell" build step. Once it has been sourced, we can use the `deploy_to_artifactory` function to perform the deployment to artifactory-qa. This function takes one argument, which the the path (which may be relative) to the RPM file to be deployed). We're checking it into the source code to make it easier to maintain through git.
RPMs are deployed to the path `cb-event-forwarder/<branch>/<platform>/<version>` on Artifactory-QA.
The script depends on three "secret" variables that specify the Jenkins API user, API key, and base URL. These would be inserted directly into the Jenkins build step -- we don't want to put them into the script file itself, because this is an opensource project (and even …

CB-30786: Jenkins script to deploy build to Artifactory-QA

---

init-scripts/cb-event-forwarder

Fixes inti.d script to return correct return codes for 'service status' and 'service stop'

cb-32416/32415: Fix status and stop return codes

---

cmd/cb-event-forwarder/pb_message_processor.go
go.mod
go.sum

Adds support for writing JA3 and JA3S fields into output from the event-forwarder.

CB-32933: Add Ja3 Ja3S support to netconv2 writer

---

conf/cb-event-forwarder.example.ini

Removes 3 deprecated config options that were used in the api-callbacks for report-title enrichment which were removed in CB-31411. 'api_url' , 'api-token', 'api_verify_ssl' - also cleans up some language in the sample config file to indicate that the cb_server_url will be set to the fqdn of the host by default.

CB-31911: Remove deprecated config options from sample config file

---

cmd/cb-event-forwarder/config.go

Adds output destination validation for the HTTP/S output - preventing the user from starting the forwarder with a misconfigured `httpout` key. The startup/config checks will fail and return an error when the destination is lacking the http(s):// protocol part.

CB-32965: Make EF protect httpoutput against misconfiguration
