main.go, static/index.html, tests/event_processing_test.go
Create human-readable status display for cb-event-forwarder
=> Status display

config.go, s3_output.go
Includes:
* Server Side Encryption
* Selectable credential profile name
* ACL policy applied to new objects uploaded to the S3 bucket
=> add more configuration options to S3 output

conf/cb-event-forwarder.example.ini, config.go, s3_output.go
Can now easily support multiple event forwarders on a single s3 bucket
=> added support for s3 object name prefixes

bundled_output.go, conf/cb-event-forwarder.example.ini, config.go, file_output.go, http_behavior.go, kafka_output.go, main.go, pb_message_processor.go, s3_behavior.go
Special thanks to @brianebeyer and @crothe for the code contribution. Changes include:
* Kafka output
* S3 output improvement: optionally gzip output files (addresses #41 - we should move this to the File handler and use the streaming compression feature before merging to master)
=> Kafka output contributed by @redcanaryco

Makefile, config.go, file_input.go, main.go
Would like to merge audit log changes into master after review
=> Auditlogging hack

cb_api.go, config.go, json_message_processor.go, main.go
Adds report link into post processing
=> Report link

pb_message_processor.go
Additional fields for child processes
=> Jan 2018 improvements

pb_message_processor.go
This adds all fields from the CbModuleInfoMsg message type into the WriteModinfoMessage func.
=> adding all fields for CbModuleInfoMsg message

cmd/cb-event-forwarder/cef_encoder_test.go, cmd/cb-event-forwarder/cef_output_test.go, cmd/cb-event-forwarder/config.go, cmd/cb-event-forwarder/main.go, internal/cef/cef_encoder.go
=> CEF output for the event forwarder

Gopkg.toml, Makefile, cmd/cb-event-forwarder/http_behavior.go, cmd/cb-event-forwarder/http_util.go, cmd/cb-event-forwarder/json_message_processor.go, cmd/cb-event-forwarder/kafka_output.go, cmd/cb-event-forwarder/main.go, cmd/cb-event-forwarder/net_output.go, cmd/cb-event-forwarder/pb_message_processor.go, cmd/cb-event-forwarder/s3_behavior.go, cmd/cb-event-forwarder/splunk_hec_behavior.go, cmd/cb-event-forwarder/syslog_output.go, internal/config/config.go, internal/output/bundled_output.go, internal/output/file_output.go, internal/output/output_handler.go, internal/util/utils.go, plugins/kafka/kafka_output.go
(Almost done)
Too unstable on MacOsx .... Works great on linux
=> Kafka confluent (Kafka updates, outputplugins)

internal/config/config.go, plugins/kafka/kafka_output.go
=> Yaml config

cmd/cb-event-forwarder/config.go, cmd/cb-event-forwarder/kafka_output.go, conf/cb-event-forwarder.example.ini
Basic support for Kafka plugin SASL authentication.
=> Support for Kafka SASL autentication

Dockerfile, Makefile, cb-event-forwarder.service, conf/cb-event-forwarder.example.ini, go.mod
Updates for Centos 7 , repairs to docker-build
=> Build updates

Makefile, cmd/cb-event-forwarder/config.go, cmd/cb-event-forwarder/event_processing_test.go, cmd/cb-event-forwarder/pb_message_processor.go, cmd/cb-event-forwarder/utils.go, go.mod
EPOCH TIME SUPPORT AS INTEGER REPRESENTATION
=> Allow users to output process-time as integer representation of epoch time

cmd/cb-event-forwarder/main.go
Thanks to @zacharyestep for the fix.
=> CB-30322: Fixing signal handling for syslog, s3 output types

Dockerfile, Dockerfile.httpserver, Dockerfile.s3server, Makefile, cb-event-forwarder.docker.ini, cb-event-forwarder.docker.kafka.ini, cb-event-forwarder.rpm.spec, cmd/cb-event-forwarder/config.go, cmd/cb-event-forwarder/file_output.go, cmd/cb-event-forwarder/http_behavior.go, cmd/cb-event-forwarder/mock_amqp.go, cmd/cb-event-forwarder/s3_behavior.go, docker-compose-kafka.yml, docker-compose.yml, go.mod, test/stress_rabbit/stress_rabbit.py
Improves throughput by using a better gzip implementation that supports parallelism over multiple core. Also touchups to the testing infrastructure and various.
=> Feature cb 31040 - Use PGZIP lib

CHANGELOG.md
=> CB-31070: CHANGELOG updates

cb-event-forwarder.service, cmd/cb-event-forwarder/main.go, go.mod, init-scripts/cb-event-forwarder
So far, the changes are only relevant to EL7+. In EL6, the init script creates and manages the PID file.
=> CB-31154: add pid file support

cb-event-forwarder.rpm.spec
hours+minutes is now hours+minutes+seconds
=> ds-fix-rpm-timestamp: what it says on the tin

CHANGELOG.md
Updated CHANGELOG.md to document bug fix for EDR Event Forwarder 3.7.1
=> Note signal handling bug fix for Event Forwarder 3.7.1

cmd/cb-event-forwarder/config.go, go.mod
Default server_name to fqdn of host and default the cb_server_url to https://fqdn in config handler
=> Feature cb 32809
